# Generated by Django 2.2.6 on 2019-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_full_name', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=10)),
                ('party_name', models.CharField(max_length=100)),
                ('office_sought', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=10)),
                ('registration_date', models.DateField()),
                ('termination_date', models.DateField()),
                ('bool_alert_sent', models.BooleanField(default=False)),
                ('ingestion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
