# Generated by Django 2.2.6 on 2019-10-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcandidate',
            name='termination_date',
            field=models.DateField(null=True),
        ),
    ]
