# Generated by Django 2.2.6 on 2019-10-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JokeResponder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('channel', models.CharField(max_length=50)),
                ('which_joke', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JokeTeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('step', models.IntegerField(default=0)),
                ('channel', models.CharField(max_length=50)),
            ],
        ),
    ]
