# Generated by Django 2.2.6 on 2019-10-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokeresponder',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
