# Generated by Django 2.2.6 on 2019-11-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=255)),
                ('meeting_id', models.IntegerField()),
                ('meeting_link', models.CharField(max_length=255)),
                ('item_title', models.CharField(max_length=255)),
                ('item_link', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('action_type', models.CharField(max_length=50)),
                ('action_taken', models.CharField(max_length=255)),
                ('bool_alert_sent', models.BooleanField(default=False)),
                ('ingestion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
