# Generated by Django 2.2.6 on 2019-11-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='meeting_type',
            field=models.CharField(choices=[('u', 'Upcoming'), ('p', 'Past')], default='p', max_length=1),
        ),
    ]
